kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: service-provider-integration-oauth

resources:
- deployment.yaml
- service-account.yaml
- service.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- oauth-service-environment-config.yaml
