# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/appstudio.redhat.com_spiaccesstokens.yaml
- bases/appstudio.redhat.com_spiaccesstokenbindings.yaml
- bases/appstudio.redhat.com_spiaccesstokendataupdates.yaml
- bases/appstudio.redhat.com_spiaccesschecks.yaml
- bases/appstudio.redhat.com_spifilecontentrequests.yaml
#+kubebuilder:scaffold:crdkustomizeresource
